// Package icons contains automatically generated byte slices containing data
// for required iconography - this is only used for the MacOS status bar app.
//
// See https://github.com/cratonica/2goarray for more information, as well as
// the build configuration.
package icons
